=== Armatiek/xslweb/XSLWeb/development/trunk/home/config/xsd/xslweb/webapp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xslweb="http://www.armatiek.com/xslweb/webapp" targetNamespace="http://www.armatiek.com/xslweb/webapp" elementFormDefault="qualified">
  <xs:element name="webapp">
    <xs:complexType>
      <xs:all>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="development-mode" type="xs:boolean" default="false"/>
        <xs:element name="max-upload-size" type="xs:integer" minOccurs="0" default="10"/>
        <xs:element minOccurs="0" name="resources">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="resource">
                <xs:complexType>
                  <xs:attribute name="pattern" type="xs:string" use="required"/>
                  <xs:attribute name="media-type" type="xs:string" use="required"/>
                  <xs:attribute name="duration" type="xs:duration" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="parameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="value" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="uri" type="xs:anyURI"/>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="type" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="xs:string"/>
                        <xs:enumeration value="xs:boolean"/>
                        <xs:enumeration value="xs:integer"/>
                        <xs:enumeration value="xs:double"/>
                        <xs:enumeration value="xs:float"/>
                        <xs:enumeration value="xs:decimal"/>
                        <xs:enumeration value="xs:integer"/>
                        <xs:enumeration value="xs:dateTime"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="jobs">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="job">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="uri" type="xs:string"/>
                    <xs:element name="cron" type="xs:string"/>
                    <xs:element name="concurrent" type="xs:boolean" minOccurs="0"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="datasources">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="datasource">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="driver-class" type="xs:string"/>
                    <xs:element name="jdbc-url" type="xs:string"/>
                    <xs:element name="username" type="xs:string" minOccurs="0"/>
                    <xs:element name="password" type="xs:string" minOccurs="0"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Armatiek/xslweb/XSLWeb/development/trunk/home/webapps/documentation/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>XSLWeb Documentation</title>
  <description>XSLWeb Documentation</description>
  <development-mode>true</development-mode>
  
  <!-- Resources to serve straight away: -->
  <resources>
    <resource pattern="/favicon.ico" media-type="image/x-icon" duration="P7DT0H0M0S"/>    
    <resource pattern="/images/.+\.png" media-type="image/png" duration="P7DT0H0M0S"/>
    <resource pattern="/images/.+\.gif" media-type="image/gif" duration="P7DT0H0M0S"/>
    <resource pattern="/images/.+\.(jpg|jpeg)" media-type="image/jpg" duration="P7DT0H0M0S"/>
    <resource pattern="/scripts/.+\.js" media-type="text/javascript" duration="P7DT0H0M0S"/>
    <resource pattern="/styles/.+\.css" media-type="text/css" duration="P7DT0H0M0S"/>           
  </resources>

  <!-- Stylesheet parameters: -->
  <parameters>
    <parameter name="foo" uri="http://www.x.y" type="xs:string">
      <value>bar</value>
    </parameter>      
  </parameters>
  
  <!-- Scheduled job definitions: -->
  <!--
  <jobs>    
    <job>
      <name></name>
      <uri></uri>
      <cron></cron>      
    </job>  
  </jobs>
  -->
  
</webapp>

=== Armatiek/xslweb/XSLWeb/development/trunk/home/webapps/my-webapp/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>My web application</title>
  <description>My web application</description>
  <development-mode>true</development-mode>
  <max-upload-size>10</max-upload-size>
  
  <!-- Resources to serve straight away: -->
  <resources>       
    <resource pattern="/images/.+\.png" media-type="image/png"/>
    <resource pattern="/images/.+\.gif" media-type="image/gif"/>
    <resource pattern="/images/.+\.(jpg|jpeg)" media-type="image/jpg"/>
    <resource pattern="/scripts/.+\.js" media-type="text/javascript"/>
    <resource pattern="/styles/.+\.css" media-type="text/css"/>
  </resources>
  
  <parameters>
    <parameter name="my-param1" uri="http://www.armatiek.com/xslweb/configuration" type="xs:string">
      <value>my-value1</value>
    </parameter>
    <parameter name="my-param2" uri="http://www.armatiek.com/xslweb/configuration" type="xs:string">
      <value>my-value2</value>
    </parameter>
  </parameters>
  
  <jobs> 
    <!--
    <job>
      <name>MyJob</name>
      <uri>my-job.html</uri>
      <cron>0/60 * * * * ?</cron> 
      <concurrent>true</concurrent>
    </job>
    -->      
  </jobs>
  
</webapp>

=== Armatiek/xslweb/XSLWeb/development/trunk/home/webapps/examples/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>XSLWeb examples</title>
  <description>XSLWeb examples</description>
  <development-mode>true</development-mode>
  <max-upload-size>10</max-upload-size> <!-- 10MB -->
  
  <!-- Resources to serve straight away: -->
  <resources> 
    <resource pattern="/(styles|images)/.+\.png" media-type="image/png"/>
    <resource pattern="/(styles|images)/.+\.gif" media-type="image/gif"/>
    <resource pattern="/(styles|images)/.+\.(jpg|jpeg)" media-type="image/jpg"/>
    <!-- Set the duration of client cache to 7 hours (default 4 hours): -->
    <resource pattern="/scripts/.+\.js" media-type="text/javascript" duration="P0DT7H0M0S"/>
    <resource pattern="/styles/.+\.css" media-type="text/css"/>
    
    <resource pattern="/downloads/.+\.docx?" media-type="application/msword"/>    
  </resources>

  <!-- Stylesheet parameters: -->
  <parameters>
    <parameter name="hostname" uri="http://www.armatiek.com/xslweb/functions/email" type="xs:string">
      <value>smtp.googlemail.com</value>
    </parameter>
    <parameter name="port" uri="http://www.armatiek.com/xslweb/functions/email" type="xs:integer">
      <value>465</value>
    </parameter>
    <parameter name="username" uri="http://www.armatiek.com/xslweb/functions/email" type="xs:string">
      <value>MYUSERNAME</value>
    </parameter>
    <parameter name="password" uri="http://www.armatiek.com/xslweb/functions/email" type="xs:string">
      <value>MYPASSWORD</value>
    </parameter>
    <parameter name="use-ssl" uri="http://www.armatiek.com/xslweb/functions/email" type="xs:boolean">
      <value>true</value>
    </parameter>
  </parameters>
  
  <!-- Scheduled job definitions: -->
  <!--
  <jobs> 
    <job>
      <name>WriteTimeJob</name>
      <uri>execute-writetime-job.html</uri>
      <cron>0/60 * * * * ?</cron>
      <concurrent>true</concurrent>
    </job>   
  </jobs>
  -->
  
  <datasources>
    <datasource>
      <name>datasource-worldcup</name>
      <driver-class>org.h2.Driver</driver-class>
      <jdbc-url>jdbc:h2:file://${webapp-dir}/xsl/relational-database/worldcup.mv</jdbc-url>
      <property name="user">sa</property>
    </datasource>
  </datasources>
  
</webapp>

=== Armatiek/xslweb/XSLWeb/development/trunk/home/webapps/ROOT/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>Root web application</title>
  <description>Root web application</description>
  <development-mode>false</development-mode>
  <max-upload-size>10</max-upload-size>
  
  <!-- Resources to serve straight away: -->
  <resources>
    <resource pattern="/favicon.ico" media-type="image/x-icon" duration="P7DT0H0M0S"/>
    <resource pattern="/robots.txt" media-type="text/plain" duration="P7DT0H0M0S"/>    
    <resource pattern="/images/.+\.png" media-type="image/png"/>
    <resource pattern="/images/.+\.gif" media-type="image/gif"/>
    <resource pattern="/images/.+\.(jpg|jpeg)" media-type="image/jpg"/>
    <resource pattern="/scripts/.+\.js" media-type="text/javascript"/>
    <resource pattern="/styles/.+\.css" media-type="text/css"/>
  </resources>
  
</webapp>

=== Armatiek/xslweb/XSLWeb/development/trunk/home/webapps/root/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>Root web application</title>
  <description>Root web application</description>
  
  <!-- Resources to serve straight away: -->
  <resources>
    <resource pattern="/favicon.ico" media-type="image/x-icon"/>    
    <resource pattern="/images/.+\.png" media-type="image/png"/>
    <resource pattern="/images/.+\.gif" media-type="image/gif"/>
    <resource pattern="/images/.+\.(jpg|jpeg)" media-type="image/jpg"/>
    <resource pattern="/scripts/.+\.js" media-type="text/javascript"/>
    <resource pattern="/styles/.+\.css" media-type="text/css"/>
  </resources>

  <!-- Stylesheet parameters: -->
  <parameters>
    <parameter name="foo" type="xs:integer">
      <value>1</value>
      <value>2</value>
      <value>3</value>
    </parameter>    
  </parameters>
  
  <!-- Scheduled job definitions: -->
  <!--
  <jobs>
    <job>
      <name></name>
      <uri></uri>
      <cron></cron>      
    </job>  
  </jobs>
  -->
  
</webapp>
