=== Armatiek/xslweb/home/config/xsd/xslweb/webapp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:xslweb="http://www.armatiek.com/xslweb/webapp" 
  targetNamespace="http://www.armatiek.com/xslweb/webapp" 
  elementFormDefault="qualified">

  <xs:import schemaLocation="../fop/fop-configuration.xsd"/>

  <xs:element name="webapp">
    <xs:complexType>
      <xs:all>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="development-mode" type="xs:boolean" default="false"/>
        <xs:element name="max-upload-size" type="xs:integer" minOccurs="0" default="10"/>
        <xs:element name="wait-for-jobs-at-close" type="xs:boolean" minOccurs="0" default="true"/>
        <xs:element minOccurs="0" name="resources">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="resource">
                <xs:complexType>
                  <xs:attribute name="pattern" type="xs:string" use="required"/>
                  <xs:attribute name="media-type" type="xs:string" use="required"/>
                  <xs:attribute name="duration" type="xs:duration" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="parameters" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="parameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="value" maxOccurs="unbounded" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="uri" type="xs:anyURI"/>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="type" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="xs:string"/>
                        <xs:enumeration value="xs:boolean"/>
                        <xs:enumeration value="xs:integer"/>
                        <xs:enumeration value="xs:double"/>
                        <xs:enumeration value="xs:float"/>
                        <xs:enumeration value="xs:decimal"/>
                        <xs:enumeration value="xs:dateTime"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="jobs">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="job">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="uri" type="xs:string"/>
                    <xs:element name="cron" type="xs:string"/>
                    <xs:element name="concurrent" type="xs:boolean" minOccurs="0"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="indexes" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="index" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="path" type="xs:string"/>
                    <xs:element name="max-term-length" type="xs:integer" minOccurs="0"/>
                    <xs:element name="index-compression" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="no_compression"/>
                          <xs:enumeration value="best_speed"/>
                          <xs:enumeration value="best_compression"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datasources" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="datasource" minOccurs="0" maxOccurs="unbounded" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="driver-class" type="xs:string"/>
                    <xs:element name="jdbc-url" type="xs:string"/>
                    <xs:element name="username" type="xs:string" minOccurs="0"/>
                    <xs:element name="password" type="xs:string" minOccurs="0"/>
                    <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="xslweb:property-type"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="fop-configs">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="fop-config">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="fop"/>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="analyzer-type">
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:anyAttribute namespace="##any" processContents="skip"/>
  </xs:complexType>
  
  <xs:simpleType name="item-type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="xs:string"/>
      <xs:enumeration value="xs:boolean"/>
      <xs:enumeration value="xs:float"/>
      <xs:enumeration value="xs:double"/>
      <xs:enumeration value="xs:long"/>
      <xs:enumeration value="xs:int"/>
      <xs:enumeration value="xs:short"/>
      <xs:enumeration value="xs:byte"/>
      <xs:enumeration value="xs:dateTime"/>
      <xs:enumeration value="xs:date"/>
      <xs:enumeration value="xs:time"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="property-type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
</xs:schema>

=== Armatiek/xslweb/home/webapps/debugger/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>XSLWeb debugger</title>
  <description>XSLWeb debugger</description>
  <development-mode>false</development-mode>
  <debug-mode>false</debug-mode>
  <max-upload-size>10</max-upload-size>
  
  <!-- Resources to serve straight away: -->
  <resources> 
    <resource pattern="/favicon.ico" media-type="image/x-icon" duration="P7DT0H0M0S"/>
    <resource pattern="/robots.txt" media-type="text/plain" duration="P1DT0H0M0S"/> 
    <resource pattern=".+\.png$" media-type="image/png"/>
    <resource pattern=".+\.gif$" media-type="image/gif"/>
    <resource pattern=".+\.(jpg|jpeg)$" media-type="image/jpg"/>
    <resource pattern=".+\.js$" media-type="text/javascript"/>
    <resource pattern=".+\.css$" media-type="text/css"/>
    <resource pattern=".+\.(ttf|woff|woff2|eot)$" media-type="application/octet-stream" duration="P1DT0H0M0S"/>
  </resources>
  
</webapp>

=== Armatiek/xslweb/home/webapps/my-webapp/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>My web application</title>
  <description>My web application</description>
  <development-mode>true</development-mode>
  <max-upload-size>10</max-upload-size>
  
  <!-- Resources to serve straight away: -->
  <resources> 
    <resource pattern="/favicon.ico" media-type="image/x-icon" duration="P7DT0H0M0S"/>
    <resource pattern="/robots.txt" media-type="text/plain" duration="P1DT0H0M0S"/> 
    <resource pattern="/images/.+\.png" media-type="image/png"/>
    <resource pattern="/images/.+\.gif" media-type="image/gif"/>
    <resource pattern="/images/.+\.(jpg|jpeg)" media-type="image/jpg"/>
    <resource pattern="/scripts/.+\.js" media-type="text/javascript"/>
    <resource pattern="/styles/.+\.css" media-type="text/css"/>
  </resources>
  
  <parameters>
    <parameter name="my-param1" uri="http://www.armatiek.com/xslweb/configuration" type="xs:string">
      <value>my-value1</value>
    </parameter>
    <parameter name="my-param2" uri="http://www.armatiek.com/xslweb/configuration" type="xs:string">
      <value>my-value2</value>
    </parameter>
  </parameters>
  
  <!--
  <jobs> 
    <job>
      <name>MyJob</name>
      <uri>my-job.html</uri>
      <cron>0/60 * * * * ?</cron> 
      <concurrent>true</concurrent>
    </job>    
  </jobs>
  -->
  
  <!--
  <datasources>
    <datasource>
      <name>my-datasource</name>
      <driver-class>org.h2.Driver</driver-class>
      <jdbc-url>jdbc:h2:file://${webapp-dir}/database/my-database.mv</jdbc-url>
      <property name="user">sa</property>
    </datasource>
  </datasources>
  -->
  
</webapp>

=== Armatiek/xslweb/home/webapps/ROOT/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>Root web application</title>
  <description>Root web application</description>
  <development-mode>false</development-mode>
  <max-upload-size>10</max-upload-size>
  
  <!-- Resources to serve straight away: -->
  <resources>
    <resource pattern="/favicon.ico" media-type="image/x-icon" duration="P7DT0H0M0S"/>
    <resource pattern="/robots.txt" media-type="text/plain" duration="P1DT0H0M0S"/>    
    <resource pattern="/images/.+\.png" media-type="image/png"/>
    <resource pattern="/images/.+\.gif" media-type="image/gif"/>
    <resource pattern="/images/.+\.(jpg|jpeg)" media-type="image/jpg"/>
    <resource pattern="/scripts/.+\.js" media-type="text/javascript"/>
    <resource pattern="/styles/.+\.css" media-type="text/css"/>
  </resources>
  
</webapp>

=== Armatiek/xslweb/home/webapps/examples/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>XSLWeb examples</title>
  <description>XSLWeb examples</description>
  
  <!-- Resources to serve straight away: -->
  <resources>
    <resource pattern="/favicon.ico" media-type="image/x-icon"/>    
    <resource pattern="/images/.+\.png" media-type="image/png"/>
    <resource pattern="/images/.+\.gif" media-type="image/gif"/>
    <resource pattern="/images/.+\.(jpg|jpeg)" media-type="image/jpg"/>
    <resource pattern="/scripts/.+\.js" media-type="text/javascript"/>
    <resource pattern="/styles/.+\.css" media-type="text/css"/>
    
    <resource pattern="/downloads/.+\.doc" media-type="application/msword"/>    
  </resources>

  <!-- Stylesheet parameters: -->
  <parameters>
    <parameter name="basex-rest-base-uri" uri="http://www.armatiek.com/xslweb/configuration" type="xs:string">
      <value>http://localhost:8984/rest</value>
    </parameter>    
  </parameters>
  
  <!-- Scheduled job definitions: -->
  <jobs>
    <job>
      <name>TestJob</name>
      <uri>http://${xslweb.localhost}:${xslweb.port}/xslweb/examples/hello-world.html</uri>
      <cron>0 11 11 11 11 ?</cron>      
    </job>  
  </jobs>
  
</webapp>

=== Armatiek/xslweb/home/webapps/xmlindex-ide/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:va="http://www.armatiek.nl/xmlindex/virtualattribute"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>XSLWeb/XMLIndex IDE</title>
  <description>XSLWeb/XMLIndex IDE</description>
  <development-mode>true</development-mode>
  <max-upload-size>100</max-upload-size>
  
  <!-- Resources to serve straight away: -->
  <resources> 
    <resource pattern="/favicon.ico" media-type="image/x-icon" duration="P7DT0H0M0S"/>
    <resource pattern="/robots.txt" media-type="text/plain" duration="P1DT0H0M0S"/> 
    <resource pattern="/.+\.png" media-type="image/png"/>
    <resource pattern="/.+\.gif" media-type="image/gif"/>
    <resource pattern="/.+\.(jpg|jpeg)" media-type="image/jpg"/>
    <resource pattern="/.+\.js" media-type="text/javascript"/>
    <resource pattern="/.+\.css" media-type="text/css"/>
    <resource pattern="/.+\.woff" media-type="application/font-woff"/>
    <resource pattern="/.+\.woff2" media-type="application/font-woff2"/>
    <resource pattern="/.+\.ttf" media-type="application/x-font-ttf"/>
  </resources>
  
  <indexes>
    
    <index>
      <name>BWB</name>
      <path>indexes/index-bwb</path>
      <max-term-length>1024</max-term-length>
      <index-compression>no_compression</index-compression>
    </index>
    
    <index>
      <name>Test Index</name>
      <path>indexes/index-tests</path>  
    </index>
    
    <index>
      <name>PUC Open Data</name>
      <path>indexes/index-pod</path>
    </index>
    
  </indexes>
  
</webapp>

=== Armatiek/xslweb/home/webapps/documentation/webapp.xml
<?xml version="1.0"?>
<webapp 
  xmlns="http://www.armatiek.com/xslweb/webapp"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.armatiek.com/xslweb/webapp ../../config/xsd/xslweb/webapp.xsd">
  
  <title>XSLWeb documentation</title>
  <description>XSLWeb documentation</description>
  <development-mode>false</development-mode>
  
  <resources>       
    <resource pattern="/.+\.html" media-type="text/html"/>
    <resource pattern="/.+\.pdf" media-type="application/pdf"/>
    <resource pattern="/XSLWeb-img/.+\.png" media-type="image/png"/>
  </resources>
  
</webapp>
